"""feat: create tables

Revision ID: aaa25c8916ef
Revises: 
Create Date: 2024-08-20 10:39:39.487852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa25c8916ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salons',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('shifts', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('order')
    )
    op.create_table('table_indexes',
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('verbose', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('col', sa.String(length=3), nullable=False),
    sa.Column('col_int', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('is_other_time', sa.Boolean(), nullable=False),
    sa.Column('cancellations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('table_indexes')
    op.drop_table('salons')
    # ### end Alembic commands ###
